In [11]:
import numpy as np
from src.dataset import *

In [12]:
mean1 = generate_mean_values(num_dist=5, min_val=-1, max_val=0)
mean1

array([[-0.13946609, -0.4137471 ],
       [-0.71651214, -0.72202249],
       [-0.54537792, -0.79458966],
       [-0.79862129, -0.48596494],
       [-0.91277063, -0.51641447]])

In [13]:
mean2 = generate_mean_values(num_dist=5, min_val=0, max_val=1)
mean2

array([[0.36217621, 0.70768662],
       [0.74674622, 0.69109292],
       [0.68918041, 0.37360012],
       [0.6681348 , 0.33984866],
       [0.57279387, 0.32580716]])

In [14]:
weight1 = generate_weights(num_dist=5)
weight1

array([0.22809982, 0.03152846, 0.12435097, 0.49786553, 0.11815523])

In [15]:
weight2 = generate_weights(num_dist=5)
weight2

array([0.22038099, 0.20731366, 0.23072685, 0.15141562, 0.19016288])

In [16]:
cov = np.array([[1,0],[0,1]])
cov

array([[1, 0],
       [0, 1]])

In [18]:
list_gauss1 = [(muy1, cov) for muy1 in mean1]
list_gauss1 

[(array([-0.13946609, -0.4137471 ]), array([[1, 0],
         [0, 1]])), (array([-0.71651214, -0.72202249]), array([[1, 0],
         [0, 1]])), (array([-0.54537792, -0.79458966]), array([[1, 0],
         [0, 1]])), (array([-0.79862129, -0.48596494]), array([[1, 0],
         [0, 1]])), (array([-0.91277063, -0.51641447]), array([[1, 0],
         [0, 1]]))]

In [19]:
list_gauss2 = [(muy2, cov) for muy2 in mean2]
list_gauss2

[(array([0.36217621, 0.70768662]), array([[1, 0],
         [0, 1]])), (array([0.74674622, 0.69109292]), array([[1, 0],
         [0, 1]])), (array([0.68918041, 0.37360012]), array([[1, 0],
         [0, 1]])), (array([0.6681348 , 0.33984866]), array([[1, 0],
         [0, 1]])), (array([0.57279387, 0.32580716]), array([[1, 0],
         [0, 1]]))]

In [21]:
sample_mixed_gauss_dist(weight1, list_gauss1, size=100)

[array([0.29848052, 1.52523136]),
 array([-0.04411206, -0.04332472]),
 array([-0.56933024,  0.22417178]),
 array([0.08674419, 0.21524376]),
 array([0.00559713, 0.75413519]),
 array([-0.62225748,  0.68885966]),
 array([-0.51135456,  0.31817422]),
 array([0.04666969, 0.80447922]),
 array([-1.65283891, -0.62742354]),
 array([ 0.68809312, -0.64560326]),
 array([-1.42941856, -0.70548613]),
 array([ 0.87282552, -1.29186206]),
 array([-1.37961778,  0.5504028 ]),
 array([-0.57287102, -0.19892978]),
 array([-1.34426014, -0.95394412]),
 array([-0.71346802,  1.11468715]),
 array([-0.63356288, -0.92121452]),
 array([-0.59672687,  0.44553691]),
 array([-0.67061347,  0.75565158]),
 array([-0.906931  ,  0.81408667]),
 array([0.69637782, 0.07837181]),
 array([-2.01952321, -0.42634951]),
 array([ 1.15433892, -0.40292853]),
 array([-1.65428738, -0.60954844]),
 array([-0.89858081, -3.35526147]),
 array([-1.28759211, -1.23252925]),
 array([-0.57035614, -0.95401736]),
 array([-2.03425791, -0.62675138]),
 a

In [22]:
sample_mixed_gauss_dist(weight2, list_gauss2, size=100)

[array([-0.47712323,  0.52090213]),
 array([0.98332691, 0.12753062]),
 array([-0.5537041,  0.3706064]),
 array([0.70392989, 0.71815699]),
 array([1.30003314, 0.29782209]),
 array([-0.95409406,  2.52508044]),
 array([-0.34158899, -0.6311561 ]),
 array([2.0332517, 0.2150892]),
 array([-1.31062996,  0.98899493]),
 array([-0.34692573,  2.17371621]),
 array([0.36862047, 0.37382667]),
 array([1.43281738, 0.50973235]),
 array([ 1.6079914 , -0.59400827]),
 array([-0.13065299,  0.5095405 ]),
 array([1.73631902, 2.03024122]),
 array([-0.36766649,  0.9340715 ]),
 array([-0.97140488,  1.0713844 ]),
 array([0.26259443, 0.29532338]),
 array([-0.32258358,  1.46118329]),
 array([2.31829239, 1.81709189]),
 array([0.77837835, 0.91939201]),
 array([-0.96560035,  1.11959234]),
 array([ 0.89200497, -0.26256519]),
 array([0.75581001, 0.127888  ]),
 array([1.90688894, 1.82079775]),
 array([0.27423455, 0.38734714]),
 array([1.4428552 , 2.00212731]),
 array([ 0.21872007, -0.59943116]),
 array([-1.02829377, -0.